
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: evendigo-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
 
    depends_on:
      - redis
    volumes:
      - ./backend/node_modules:/app/node_modules  
    networks:
      - evendigo-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      -  evendigo-network

volumes:
  redis_data:

networks:
  evendigo-network:
    driver: bridge